/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import static java.awt.Frame.MAXIMIZED_BOTH;

/**
 *
 * @author Romildo A. Lima Jr.
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        telaInterna = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuCadFisica = new javax.swing.JMenuItem();
        menuCadJuridica = new javax.swing.JMenuItem();
        menuCadUsuario = new javax.swing.JMenuItem();
        menuConsulta = new javax.swing.JMenu();
        menuConFisica = new javax.swing.JMenuItem();
        menuConJuridica = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        menuSairUsuario = new javax.swing.JMenuItem();
        menuSairSistema = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout telaInternaLayout = new javax.swing.GroupLayout(telaInterna);
        telaInterna.setLayout(telaInternaLayout);
        telaInternaLayout.setHorizontalGroup(
            telaInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );
        telaInternaLayout.setVerticalGroup(
            telaInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );

        menuCadastro.setText("Cadastro");

        menuCadFisica.setText("Física");
        menuCadFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadFisicaActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadFisica);

        menuCadJuridica.setText("Jurídica");
        menuCadastro.add(menuCadJuridica);

        menuCadUsuario.setText("Usuário");
        menuCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadUsuarioActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadUsuario);

        jMenuBar1.add(menuCadastro);

        menuConsulta.setText("Consulta");

        menuConFisica.setText("Pessoa Física");
        menuConsulta.add(menuConFisica);

        menuConJuridica.setText("Pessoa Jurídica");
        menuConsulta.add(menuConJuridica);

        jMenuBar1.add(menuConsulta);

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });

        menuSairUsuario.setText("Trocar Usuário");
        menuSair.add(menuSairUsuario);

        menuSairSistema.setText("Sair do Sistema");
        menuSairSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairSistemaActionPerformed(evt);
            }
        });
        menuSair.add(menuSairSistema);

        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaInterna)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaInterna)
        );

        setSize(new java.awt.Dimension(665, 545));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuSairSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairSistemaActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuSairSistemaActionPerformed

    private void menuCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadUsuarioActionPerformed
        // TODO add your handling code here:
        
        TelaUsuario usuario = new TelaUsuario();
        usuario.setVisible(true);
        telaInterna.add(usuario);
        
        
    }//GEN-LAST:event_menuCadUsuarioActionPerformed

    private void menuCadFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadFisicaActionPerformed
        // TODO add your handling code here:
        TelaDevedor devedor = new TelaDevedor();
        telaInterna.add(devedor);
        devedor.setVisible(true);
    }//GEN-LAST:event_menuCadFisicaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuCadFisica;
    private javax.swing.JMenuItem menuCadJuridica;
    private javax.swing.JMenuItem menuCadUsuario;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuConFisica;
    private javax.swing.JMenuItem menuConJuridica;
    private javax.swing.JMenu menuConsulta;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem menuSairSistema;
    private javax.swing.JMenuItem menuSairUsuario;
    private javax.swing.JDesktopPane telaInterna;
    // End of variables declaration//GEN-END:variables
}
